name = "www"
main = "src/worker.ts"
compatibility_date = "2023-06-16"

# KV Namespace binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/kv
[[kv_namespaces]]
binding = "ORDER"
id = "decb2661e272460eaf4c6d4d687e04ef"
preview_id = "decb2661e272460eaf4c6d4d687e04ef"

[[kv_namespaces]]
binding = "COMMENT"
id = "5c50e8791ce34883be21dcd02e97af4d"
preview_id = "5c50e8791ce34883be21dcd02e97af4d"

# # Durable Object binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/durable-objects
# [[durable_objects]]
# binding = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"

# # R2 Bucket binding - For more information: https://developers.cloudflare.com/r2/api/workers/workers-api-reference/#create-a-binding
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"

# # Service binding - For more information: https://developers.cloudflare.com/workers/platform/services
# [[routes]]
# binding = "MY_SERVICE"
# pattern = "/api/*"
# script = "api.js"

# # Queue binding - For more information: https://developers.cloudflare.com/workers/runtime-apis/queues
# [[queues]]
# binding = "MY_QUEUE"
# name = "my-queue"
# zone_id = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"

# [env.production]
# MY_VARIABLE = "production_value"

# [env.staging]
# MY_VARIABLE = "staging_value"

# [env.shared]
# SHARED_VARIABLE = "shared_value"
